# Most of the parameters will be imported from the training config
src:
  ckpt: 'rnnt_latest.pth'
  config: 'config/dlhlp/asr_dlhlp_layer5_w_pretrained_rnnt.yaml'
data:
  corpus:
    name:  'dlhlp'
    dev_split: ['dev']
    test_split: ['test']
decode:
  beam_size: 5
  min_len_ratio: 0.01
  max_len_ratio: 0.30
  lm_path: 'ckpt/lm_dlhlp_sd0/best_ppx.pth'
  lm_config: 'config/dlhlp/lm_dlhlp.yaml'
  lm_weight: 0.5
  ctc_weight: 0.0
  output_file: 'OUTPUT_FILE_TO_BE_CHANGED'
  kaggle_format: true